-- === Таблица пользователей ===
CREATE TABLE IF NOT EXISTS users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  created_at TIMESTAMP,
  updated_at TIMESTAMP,
  email VARCHAR(255) NOT NULL,
  password VARCHAR(255) NOT NULL,
  username VARCHAR(50) NOT NULL,
  CONSTRAINT users_pkey PRIMARY KEY (id),
  CONSTRAINT uk_email UNIQUE (email),
  CONSTRAINT uk_username UNIQUE (username)
);

-- === Таблица предметов ===
CREATE TABLE IF NOT EXISTS items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  created_at TIMESTAMP,
  updated_at TIMESTAMP,
  title VARCHAR(50) NOT NULL,
  description VARCHAR(100) NOT NULL,
  user_id BIGINT,
  CONSTRAINT items_pkey PRIMARY KEY (id),
  CONSTRAINT uk_title UNIQUE (title),
  CONSTRAINT fk_user FOREIGN KEY (user_id) REFERENCES users (id)
);

-- === Индексы Flyway оставляем в покое ===
-- CREATE INDEX flyway_schema_history_s_idx ON flyway_schema_history(success);
-- Не создаём этот индекс вручную, Flyway сам его создаёт при инициализации

