CREATE TABLE users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  created_at TIMESTAMP,
  updated_at TIMESTAMP,
  email VARCHAR(255) NOT NULL,
  password VARCHAR(255) NOT NULL,
  username VARCHAR(50) NOT NULL,
  CONSTRAINT users_pkey PRIMARY KEY (id),
  CONSTRAINT uk_email UNIQUE (email),
  CONSTRAINT uk_username UNIQUE (username)
);

CREATE TABLE items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  created_at TIMESTAMP,
  updated_at TIMESTAMP,
  title VARCHAR(50) NOT NULL,
  description VARCHAR(100) NOT NULL,
  user_id BIGINT,
  CONSTRAINT items_pkey PRIMARY KEY (id),
  CONSTRAINT uk_title UNIQUE (title),
  CONSTRAINT fk_user FOREIGN KEY (user_id) REFERENCES users (id)
);

CREATE INDEX flyway_schema_history_s_idx ON flyway_schema_history(success);
